<?php

return array(
    '' => '---',
    '0' => 'Success',
    '1000' => 'Purchase registration success',
    '3001' => 'Duplication request.',
    '3002' => 'Unenrolled IP.',
    '3003' => 'Not the duration of campaign.',
    '3004' => 'Goods allowed quantity has been exceeded.',
    '3999' => 'Error occurrence during checking Parameter',
    '3912' => 'Invalid medium ID.',
    '3913' => 'No registered goods in medium.',
    '3301' => 'Goods Id is nonexistent.',
    '3302' => 'Invalid goods Id.',
    '3401' => 'Goods quantity is nonexistent.',
    '3402' => 'Invalid number.',
    '3501' => 'Phone number is nonexistent.',
    '3502' => 'Invalid phone number.',
    '3503' => 'Unsupported MMS',
    '3504' => 'Invalid phone number foam',
    '3601' => 'Callback number is nonexistent',
    '3602' => 'Invalid callback number',
    '3701' => 'Campaign name is nonexistent',
    '3702' => 'Phone Number Exceed acceptable length',
    '3801' => 'Message is nonexistent',
    '3802' => 'Message Exceed acceptable length',
    '3901' => 'Intrinsic Id is nonexistent',
    '3902' => 'Exceed acceptable length',
    '3201' => 'Reservation date is nonexistent',
    '3204' => 'Reservation date is possible to after 5 min. to 90days',
    '2001' => 'Invalid purchase number',
    '2002' => 'Error during issuing Private pin',
    '2003' => 'Lack of public pin’s residual quantity. Public pin
    additional registration request.',
    '2004' => 'No data for making valid pin',
    '2005' => 'Error to input new pin information',
    '2006' => 'An error occurred while issuing the new pin’s detail
    information.',
    '2007' => 'An error occurred while changing the purchase status',
    '2008' => 'Issuance was successful, but an error occurred while
    sending MMS.
    Try resending.',
    '2999' => 'Error during issuing a voucher',
    '4000' => 'Fail to issue voucher',
    '4001' => 'Fail to registration',
    '4002' => 'Fail to inquiry voucher',
    '4003' => 'Voucher cannot be canceled etc.[status]',
    '4004' => 'Impossible to cancel voucher [error during cancel public
    pin]',
    '4005' => 'Canceled voucher.',
    '4006' => 'Used voucher is impossible to cancel',
    '4007' => 'Voucher is expired',
    '4009' => 'Error during cancel voucher',
    '4010' => 'Error during using vouche',
    '4011' => 'Exceed the issue limit.',
    '5001' => 'Fail to re-send MMS [Attempting to send]',
    '5002' => 'Impossible to re-send MMS [status]',
    '5003' => 'Number of try(attempts) exceed',
    '6001' => 'Balance management function is not set',
    '9991' => 'No MMS result',
    '9999' => 'Internal system error'
);